CREATE TABLE IF NOT EXISTS TRANSACTION(
CUSTOMER_KEY CHAR(8) NOT NULL
,CURRENCY CHAR(3) NOT NULL
,SUFFIX CHAR(3) NOT NULL
,NARRATIVE_ID INT NOT NULL
,TRANSACTION_AMOUNT INT NOT NULL
,VALUE_DATE DATE NOT NULL
,POSTED_DATE DATE NOT NULL
,PRIMARY KEY (CUSTOMER_KEY,CURRENCY,SUFFIX)
);
CREATE TABLE IF NOT EXISTS NARRATIVE(
 NARRATIVE_ID INT NOT NULL
,SEQUENCE_NUMBER INT NOT NULL
,NARRATIVE_DESCRIPTION VARCHAR(200)NOT NULL
,PRIMARY KEY (NARRATIVE_ID,SEQUENCE_NUMBER)
);
COMMIT;